### ISSUE TITLE
Generate and host HTML

### ISSUE THREAD

**Issue by fmap** [fmap/muflax65ngodyewp.onion#2]
- [x] Write enough Nix to declare a build environment

**Comment by ghost** [comment]
~~mumblegrumble gravediggers mumblegrumble~~

Good luck with re-generating this. I have an old /vendor dump in my archives that builds the latest version, but I remember the nanoc setup was super-fragile and recent versions of various gems broke the site, so yeah.

(Also, if you figure out how to sanely turn a Bundler setup into a Nix environment, tell me, that's somewhere on my todo...)

**Comment by fmap** [comment]
@muflax  ([bundler-env](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/ruby/bundler-env/default.nix) looks promising -- [here's an example](https://github.com/NixOS/nixpkgs/tree/master/pkgs/servers/monitoring/riemann-dash) -- but it looks like they've been writing out gem sets manually? Shouldn't be too hard to automate providing you have a reliable parser for Gemfiles. That said, I haven't tried using it for anything yet...)
